version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: pi-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pg_recipes_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: pi-fastapi
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql+psycopg://postgres:mypassword@db:5432/postgres

volumes:
  pg_recipes_data: